<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" /> 
<link rel="stylesheet" type="text/css" href="/css/product_info.css" /> 
<link rel="stylesheet" type="text/css" href="/css/960.css" /> 
<script type="text/javascript" src="/js/site.js"></script>
<script type="text/javascript" src="/js/jquery-1.4</script>.4.min.js">
<script type="text/javascript" src="/js/slideshow.js"></script>
<script type="text/javascript">	

			function currency_translate2(){
				var currency=document.getElementById('currency_convert2');
  			
  			if(currency.value!="no"){
      		currency_value=currency.value;
      		//Get Currency Type

      		var code=currency_value.substring(currency_value.length-3,currency_value.length);
      		//Get the Exchange Rate

      		var currency=currency_value.substring(0,currency_value.length-4);
      		var price_now=document.getElementById('newPrice_label');
      		var HK_price=document.getElementById('HK_price');
      		var final_price=currency*HK_price.value;
      		
      		price_now.innerHTML=code+'$'+final_price.toFixed(2); // ** Update the Price in another Currency

  			}
  		}

  		$(document).ready(function() {
				 // (a little sooner than page load)

				  $('#extraInfo_Area').hide();
				  $('a#extraInfo_link').click(function() {
				    $('#extraInfo_Area').toggle(300);
				    return false;
				  });
				});
				  
				 
			
</script>
<center> 
 <table>
 	<tr>
 		<td>
 <h1><?=$this->escape($this->title);?></h1>
  <div id="description">
    <?=$this->escape($this->description);?>
  </div>
  <form name="detail" method="post" action="<?=$this->escape($this->action)?>">
  <table>
  <div id="bookinfo" align="center">
  <tr>
			<td class="field">Title</td>
			<td class="value"><?=$this->book->name?>&nbsp;</td>
	</tr>	
  <tr>
			<td class="field">Author</td>
			<td class="value"><?=$this->book->author?>&nbsp;</td>
		</tr>	
		<tr>
			<td class="field">Publisher</td>
			<td class="value"><?=$this->book->publisher?>&nbsp;</td>
		</tr>
		<tr>
			<td class="field">ISBN</td>
			<td class="value"><?=$this->book->isbn?>&nbsp;</td>
		</tr>
	 	<tr>
			<td class="field">Classification</td>
			<td class="value"><?=$this->book->categoryId?>&nbsp;</td>
		</tr>
		<tr>
			<td class="field">Price</td>
			<td class="value"><span id="newPrice_label">HK$<?=$this->book->price?>&nbsp;<span></td>
		</tr>
		<tr style="display:none;">
			<td class="field">&nbsp;</td>
			<td class="value">
				<select id="" name="" id="productInfo_currency_select"></select>
					<div id="">Exchange Rate is just for reference</div>
			</td>
		</tr>
		<tr>
			<td class="field">Exchange Rate Reference</td>
			<td class="value">
				<form id="productInfo_currency" action="bookinfo1.php?bid=<? echo $bid; ?>">
	      	<INPUT type="hidden" id="HK_price" value="<?=$this->book->price?>&nbsp;"> 
					<select id="currency_convert2" name="currency_convert2" onchange="currency_translate2()" id="productInfo_currency_select">
						<option value="no" selected="selected">Exchange Rate</option>
						<option label="HKD" value="1.00000000HKD">HKD</option>
						<option label="USD" value="0.12840000USD">USD</option>
						<option label="RMB" value="0.89920002RMB">RMB</option>
						<option label="TWD" value="3.90300012TWD">TWD</option>
						<option label="JPY" value="13.17300034JPY">JPY</option>
						<option label="CAD" value="0.12909999CAD">CAD</option>
						<option label="EUR" value="0.08190000EUR">EUR</option>
					</select>
				</form>
			</td>
		</tr>
   		<!--
			***** Add the Book Image Here ****         
		-->
		<tr>
			<td class="productImg" rowspan="13" colspan="2">
				<table width="100">
					<tbody>
						<tr>
							<td>
									<div class="container_12" id="wrapper"> 
							      <div class="grid_8" id="content">
							       	<div class="grid_6 prefix_1 suffix_1" id="gallery"> 
							        	
							          <div id="pictures"> 
							              <img src="/images/books/<?=$this->book->isbn?>-12.png" alt="" /> 
														<img src="/images/books/<?=$this->book->isbn?>-11.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-10.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-09.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-08.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-07.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-06.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-05.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-04.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-03.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-02.png" alt="" />
														<img src="/images/books/<?=$this->book->isbn?>-01.png" alt="" />
							            </div>  
							          <div class="grid_3 alpha" id="prev"> 
							            <a href="#previous">&laquo; Previous page</a>  
							          </div> 
							          <div class="grid_3 omega" id="next"> 
							            <a href="#next">Next page &raquo;</a> 
							          </div>         
							        </div> 
							        
							      </div> 
							    </div>
								</td>
							</tr>
						</tbody>
					</table>
			</td>
		</tr>		
  </div>
    <tr align="right"><td colspan="2" align="right">
    
  <input type="hidden" name="id" value="<?=$this->book->id?>">

  </td></tr>
  </form>
  </table>  
  </td> 
  </tr> 
 </table>
</center>