<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" /> 

  <div class="banner">
    <span class="title">Start a journey with one of our selected books</span>
    <h1>Online Bookstore</h1>
    <img class="arrow" src="/images/arrow.svg" alt="Down arrow">
  </div>


 <div class = "container" id="main-container">
     <article class = "book-table">

         <?foreach($this->books as $book){?>
             <div class = "thumbnail">
                 <table>
                     <thead>
                     <tr>
                         <th colspan="2" class="table-top">cover</th>
                     </tr>
                     </thead>
                     <tbody>
                     <tr class = "data">
                         <td colspan="2"><img width="200" src="/<?= $book->imageUrl ?>"/></td>
                     </tr>
                     <tr class ="data">
                         <td colspan="2" class="img-url"><a href="./detail/id/<?= $book->id?>"><?= $book->imageUrl ?>"/></a>&nbsp;</td>
                     </tr>
                     <tr class ="data">
                         <th scope = "row">Title</th>
                         <td><a href="./detail/id/<?= $book->id ?>"><?= $book->name?></a>&nbsp;</td>
                     </tr>
                     <tr class ="data">
                         <th scope ="row">Author</th>
                         <td><?=$book->author?>&nbsp;</td>
                     </tr>
                     <tr class ="data">
                         <th scope ="row">Price</th>
                         <td>$ <?=$book->price?>&nbsp;</td>
                     </tr>
                     <tr class ="data">
                         <th scope= "row">Category</th>
                         <td><?=$book->categoryId?>&nbsp;</td>
                     </tr>
                     </tbody>
                 </table>
             </div>
         <? } ?>

     </article>
     <aside class="search">
        <div id="add-new">
         <!-- for home exercise -->
         <h2 id="add-book"><a href="<?php echo $this->url(
                 array(
                     'controller' => 'books',
                     'action'     => 'insert'
                 ),
                 'default',
                 true) ?>">Add a new Book</a></h2>
         <!--- end home exercise -->
        </div>
         <form action="app.js">
             <h2>Search book</h2>
             <input type="text" placeholder="Search your book by title name" name="title" id="search" required>
             <button type="submit"> Search </button>
         </form>
     </aside>


 </div>

<script src="/js/app.js"></script>
