<html> 
<head> 
<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" />
 <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>

<title>Online Book Store</title> 
</head>
<body>

  <header class="main-header">
   <h1 class="name"><a href="#"><img src="/images/logo.jpg" border="0"  width="80"></a></h1>
   <nav>
   <ul class="main-nav">
    <li><a href="/books">Home</a></li>
    <li><a href="#">Members</a></li>
    <li><a href="#">Cart</a></li>
    <li><a href="/authentication/login">Login</a></li>
    <li><a href="/#">Contact</a></li>
   </ul>
   </nav>
  </header><!--/.main-header-->



