<html> 
<head> 
<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" />
 <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>

<title>Online Book Store</title> 
</head>
<body>

  <header class="main-header">
   <h1 class="name"><a href="/books"><img src="/images/logo.jpg" border="0"  width="80"></a></h1>
   <nav>
   <ul class="main-nav">
    <li><a href="/books">Home</a></li>

    <!--/.if logged in when member is clicked, direct to edit, else to signup-->
    <li><a href=  <?php
     $auth = Zend_Auth::getInstance();
     if ($auth->hasIdentity()) {
      echo '/Authentication/edit/id/'.$auth->getIdentity()->member_id;
     } else {
      echo "/Authentication/signup";
     }?>>Members</a></li>
    <li><a href="#">Cart</a></li>

    <!--/.if logged in no Login tab, else add login and signup tabs-->
    <?php
    $auth = Zend_Auth::getInstance();
    if ($auth->hasIdentity()) {
    } else {
     echo '<li><a href="/authentication/login">Login</a></li><li><a href="/authentication/signup">Signup</a></li>';
    }?>
    <li><a href="/#">Contact</a></li>
   </ul>
   </nav>
  </header><!--/.main-header-->



